import { useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import { AudioModule, RecordingPresets, setAudioModeAsync, useAudioRecorder, useAudioRecorderState } from 'expo-audio';
import { Screen } from '../src/components/Screen';
import { PrimaryButton } from '../src/components/PrimaryButton';
import { useWorkspace } from '../src/providers/workspace-provider';
import { analyzeImage, manualDraft, structureText, transcribeAudio } from '../src/services/api';
import { clearRawDraft, loadRawDraft, savePendingDraft, saveRawDraft } from '../src/services/drafts';
import { createFieldEntry, updateFieldEntry } from '../src/services/findings';
import { uploadLocalFile } from '../src/services/upload';
import { theme } from '../src/theme';

type Mode='text'|'audio'|'photo';
export default function Register(){const{workspace}=useWorkspace();const[mode,setMode]=useState<Mode>('text');const[text,setText]=useState('');const[busy,setBusy]=useState(false);const recorder=useAudioRecorder({...RecordingPresets.HIGH_QUALITY,directory:'document'});const recorderState=useAudioRecorderState(recorder);useEffect(()=>{void loadRawDraft().then(d=>{if(d?.text)setText(d.text)});void AudioModule.requestRecordingPermissionsAsync();void setAudioModeAsync({playsInSilentMode:true,allowsRecording:true});},[]);
async function finish(fieldEntryId:string,raw:string,draft:any,dueAt:string|null,provider:string,capturePath?:string){await savePendingDraft({fieldEntryId,rawText:raw,draft,dueAt,provider,capturePath});await clearRawDraft();router.push('/review-draft')}
async function processText(){if(!workspace||text.trim().length<3)return Alert.alert('Falta el hallazgo','Escribí al menos una frase.');setBusy(true);await saveRawDraft({mode:'text',text,savedAt:new Date().toISOString()});try{const fieldId=await createFieldEntry(workspace,'text',text.trim());try{const result=await structureText(text.trim());await finish(fieldId,text.trim(),result.draft,result.due_at,result.provider)}catch{await finish(fieldId,text.trim(),manualDraft(text.trim()),null,'manual')}}catch(e){Alert.alert('Guardado local',`No pudimos sincronizar todavía. La nota queda en el teléfono. ${e instanceof Error?e.message:''}`)}finally{setBusy(false)}}
async function pickPhoto(){if(!workspace)return;const permission=await ImagePicker.requestCameraPermissionsAsync();if(!permission.granted)return Alert.alert('Cámara','Necesitamos permiso de cámara.');const result=await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.75});if(result.canceled)return;setBusy(true);await saveRawDraft({mode:'photo',text,savedAt:new Date().toISOString()});try{const fieldId=await createFieldEntry(workspace,'photo',text.trim()||null);const asset=result.assets[0];const upload=await uploadLocalFile({bucket:'hse-captures',organizationId:workspace.organizationId,entityId:`field-entries/${fieldId}`,uri:asset.uri,mimeType:asset.mimeType||'image/jpeg',prefix:'photo'});await updateFieldEntry(fieldId,{photo_storage_paths:[upload.path],metadata:{original_file_name:asset.fileName||null}});try{const ai=await analyzeImage(asset.uri,text.trim());await finish(fieldId,text.trim(),ai.draft,null,ai.provider,upload.path)}catch{await finish(fieldId,text.trim(),manualDraft(text.trim()||'Evidencia fotográfica pendiente de revisar'),null,'manual',upload.path)}}catch(e){Alert.alert('No se pudo registrar',e instanceof Error?e.message:'Error')}finally{setBusy(false)}}
async function toggleAudio(){if(!workspace)return;if(recorderState.isRecording){setBusy(true);try{await recorder.stop();const uri=recorder.uri;if(!uri)throw new Error('No se generó el audio');const fieldId=await createFieldEntry(workspace,'audio',null);const upload=await uploadLocalFile({bucket:'hse-captures',organizationId:workspace.organizationId,entityId:`field-entries/${fieldId}`,uri,mimeType:'audio/mp4',prefix:'voice'});await updateFieldEntry(fieldId,{audio_storage_path:upload.path});try{const tr=await transcribeAudio(uri);await updateFieldEntry(fieldId,{raw_text:tr.text});try{const structured=await structureText(tr.text);await finish(fieldId,tr.text,structured.draft,structured.due_at,`${tr.provider}+${structured.provider}`,upload.path)}catch{await finish(fieldId,tr.text,manualDraft(tr.text),null,tr.provider,upload.path)}}catch{await finish(fieldId,'',manualDraft('Audio pendiente de transcripción manual'),null,'manual',upload.path)}}catch(e){Alert.alert('Audio',e instanceof Error?e.message:'Error')}finally{setBusy(false)}}else{const p=await AudioModule.requestRecordingPermissionsAsync();if(!p.granted)return Alert.alert('Micrófono','Necesitamos permiso para grabar.');await recorder.prepareToRecordAsync();recorder.record()}}
return <Screen><View style={styles.head}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Volver</Text></Pressable><Text style={styles.title}>Registrar</Text></View><View style={styles.switch}>{(['text','audio','photo'] as Mode[]).map(x=><Pressable key={x} onPress={()=>setMode(x)} style={[styles.mode,mode===x&&styles.modeOn]}><Text style={[styles.modeText,mode===x&&styles.modeTextOn]}>{x==='text'?'✍️ Texto':x==='audio'?'🎙️ Voz':'📷 Foto'}</Text></Pressable>)}</View>{mode==='text'?<><Text style={styles.label}>Contá lo que viste como lo dirías normalmente.</Text><TextInput multiline placeholder="Ej.: Sala de bombas. Hay una pérdida en la manguera hidráulica. Que mantenimiento la revise mañana." value={text} onChangeText={setText} style={styles.textarea}/><PrimaryButton title="Estructurar hallazgo" busy={busy} onPress={()=>void processText()}/></>:null}{mode==='audio'?<View style={styles.center}><Pressable onPress={()=>void toggleAudio()} style={[styles.audio,recorderState.isRecording&&styles.recording]}><Text style={styles.audioIcon}>{recorderState.isRecording?'■':'🎙️'}</Text></Pressable><Text style={styles.audioTitle}>{recorderState.isRecording?'Grabando… tocá para terminar':'Tocá y hablá'}</Text><Text style={styles.label}>{recorderState.isRecording?`${Math.round(recorderState.durationMillis/1000)} s`:'El audio original queda guardado como evidencia de captura.'}</Text></View>:null}{mode==='photo'?<><Text style={styles.label}>Podés agregar una nota antes de sacar la foto.</Text><TextInput multiline placeholder="Nota opcional" value={text} onChangeText={setText} style={styles.textarea}/><PrimaryButton title="Abrir cámara" busy={busy} onPress={()=>void pickPhoto()}/></>:null}</Screen>}
const styles=StyleSheet.create({head:{gap:8},back:{color:theme.colors.primary,fontWeight:'800'},title:{fontSize:32,fontWeight:'900',color:theme.colors.ink},switch:{flexDirection:'row',gap:8},mode:{flex:1,paddingVertical:12,borderRadius:13,backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,alignItems:'center'},modeOn:{backgroundColor:theme.colors.primary,borderColor:theme.colors.primary},modeText:{fontWeight:'800',color:theme.colors.muted,fontSize:12},modeTextOn:{color:'#fff'},label:{color:theme.colors.muted,lineHeight:20},textarea:{minHeight:150,backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:16,padding:15,textAlignVertical:'top',fontSize:16},center:{flex:1,alignItems:'center',justifyContent:'center',gap:16},audio:{width:150,height:150,borderRadius:75,backgroundColor:theme.colors.primary,alignItems:'center',justifyContent:'center'},recording:{backgroundColor:theme.colors.danger},audioIcon:{fontSize:48,color:'#fff'},audioTitle:{fontSize:20,fontWeight:'900',color:theme.colors.ink}});
