import type { NormativeItem } from '@/types/normative';

export const baseNormatives: NormativeItem[] = [
  {
    id: 'ley-19587',
    jurisdiction: 'nacional',
    type: 'Ley',
    number: '19.587',
    year: 1972,
    title: 'Higiene y Seguridad en el Trabajo',
    summary: 'Marco nacional general de higiene y seguridad en el trabajo para establecimientos y actividades laborales.',
    topics: ['Higiene y Seguridad', 'HSE', 'Trabajo'],
    modules: ['hse', 'oil-gas', 'construction', 'maintenance'],
    organism: 'Congreso de la Nación Argentina',
    status: 'vigente',
    officialSourceLabel: 'Fuente oficial pendiente',
    tags: ['seguridad', 'trabajo', 'base legal']
  },
  {
    id: 'dec-351-79',
    jurisdiction: 'nacional',
    type: 'Decreto',
    number: '351/79',
    year: 1979,
    title: 'Reglamentario de la Ley 19.587',
    summary: 'Reglamentación general sobre condiciones de higiene y seguridad en el trabajo.',
    topics: ['Higiene y Seguridad', 'Condiciones de trabajo'],
    modules: ['hse', 'maintenance'],
    organism: 'Poder Ejecutivo Nacional',
    status: 'vigente',
    officialSourceLabel: 'Fuente oficial pendiente',
    tags: ['condiciones', 'seguridad', 'reglamentación']
  },
  {
    id: 'ley-24557',
    jurisdiction: 'nacional',
    type: 'Ley',
    number: '24.557',
    year: 1995,
    title: 'Riesgos del Trabajo',
    summary: 'Marco nacional de riesgos del trabajo, ART, prevención y reparación de contingencias laborales.',
    topics: ['ART', 'Riesgos del trabajo', 'Prevención'],
    modules: ['hse'],
    organism: 'Congreso de la Nación Argentina',
    status: 'vigente',
    officialSourceLabel: 'Fuente oficial pendiente',
    tags: ['art', 'prevención', 'riesgos']
  },
  {
    id: 'dec-911-96',
    jurisdiction: 'nacional',
    type: 'Decreto',
    number: '911/96',
    year: 1996,
    title: 'Seguridad para la Industria de la Construcción',
    summary: 'Reglamento de higiene y seguridad específico para actividades de construcción.',
    topics: ['Construcción', 'Seguridad en obra', 'Obra'],
    modules: ['construction', 'hse'],
    organism: 'Poder Ejecutivo Nacional',
    status: 'vigente',
    officialSourceLabel: 'Fuente oficial pendiente',
    tags: ['obra', 'construcción', 'seguridad']
  },
  {
    id: 'srt-295-2003',
    jurisdiction: 'nacional',
    type: 'Resolución SRT',
    number: '295/2003',
    year: 2003,
    title: 'Contaminantes, ergonomía, carga térmica, ruido y vibraciones',
    summary: 'Referencias técnicas vinculadas a agentes de riesgo físico, químico y ergonómico.',
    topics: ['Ruido', 'Ergonomía', 'Carga térmica', 'Contaminantes'],
    modules: ['hse', 'oil-gas', 'maintenance'],
    organism: 'Superintendencia de Riesgos del Trabajo',
    status: 'vigente',
    officialSourceLabel: 'Fuente oficial pendiente',
    tags: ['ruido', 'ergonomía', 'mediciones']
  },
  {
    id: 'srt-299-2011',
    jurisdiction: 'nacional',
    type: 'Resolución SRT',
    number: '299/2011',
    year: 2011,
    title: 'Entrega y certificación de Elementos de Protección Personal',
    summary: 'Registro y constancia de entrega de EPP al personal.',
    topics: ['EPP', 'Registro', 'Protección personal'],
    modules: ['hse', 'oil-gas', 'construction'],
    organism: 'Superintendencia de Riesgos del Trabajo',
    status: 'vigente',
    officialSourceLabel: 'Fuente oficial pendiente',
    tags: ['epp', 'registro', 'protección']
  },
  {
    id: 'srt-84-2012',
    jurisdiction: 'nacional',
    type: 'Resolución SRT',
    number: '84/2012',
    year: 2012,
    title: 'Protocolo de medición de iluminación',
    summary: 'Protocolo aplicable para mediciones de iluminación en ambientes laborales.',
    topics: ['Iluminación', 'Mediciones'],
    modules: ['hse'],
    organism: 'Superintendencia de Riesgos del Trabajo',
    status: 'vigente',
    officialSourceLabel: 'Fuente oficial pendiente',
    tags: ['iluminación', 'medición']
  },
  {
    id: 'srt-85-2012',
    jurisdiction: 'nacional',
    type: 'Resolución SRT',
    number: '85/2012',
    year: 2012,
    title: 'Protocolo de medición de ruido',
    summary: 'Protocolo aplicable para mediciones de ruido en el ámbito laboral.',
    topics: ['Ruido', 'Mediciones'],
    modules: ['hse', 'oil-gas'],
    organism: 'Superintendencia de Riesgos del Trabajo',
    status: 'vigente',
    officialSourceLabel: 'Fuente oficial pendiente',
    tags: ['ruido', 'medición']
  },
  {
    id: 'srt-886-2015',
    jurisdiction: 'nacional',
    type: 'Resolución SRT',
    number: '886/2015',
    year: 2015,
    title: 'Ergonomía y levantamiento manual de cargas',
    summary: 'Herramienta técnica vinculada a evaluación ergonómica y manipulación manual de cargas.',
    topics: ['Ergonomía', 'Levantamiento manual de cargas'],
    modules: ['hse', 'maintenance'],
    organism: 'Superintendencia de Riesgos del Trabajo',
    status: 'vigente',
    officialSourceLabel: 'Fuente oficial pendiente',
    tags: ['ergonomía', 'cargas']
  },
  {
    id: 'srt-900-2015',
    jurisdiction: 'nacional',
    type: 'Resolución SRT',
    number: '900/2015',
    year: 2015,
    title: 'Puesta a tierra y continuidad eléctrica',
    summary: 'Protocolo de medición y control de puesta a tierra y continuidad de masas.',
    topics: ['Electricidad', 'PAT', 'Disyuntores'],
    modules: ['hse', 'oil-gas', 'maintenance'],
    organism: 'Superintendencia de Riesgos del Trabajo',
    status: 'vigente',
    officialSourceLabel: 'Fuente oficial pendiente',
    tags: ['electricidad', 'pat', 'medición']
  },
  {
    id: 'ley-25675',
    jurisdiction: 'nacional',
    type: 'Ley',
    number: '25.675',
    year: 2002,
    title: 'Ley General del Ambiente',
    summary: 'Marco nacional de política ambiental, principios de prevención, recomposición y gestión ambiental.',
    topics: ['Ambiente', 'Gestión ambiental', 'Prevención'],
    modules: ['environment', 'hse', 'oil-gas'],
    organism: 'Congreso de la Nación Argentina',
    status: 'vigente',
    officialSourceLabel: 'Fuente oficial pendiente',
    tags: ['ambiente', 'prevención']
  },
  {
    id: 'ley-24051',
    jurisdiction: 'nacional',
    type: 'Ley',
    number: '24.051',
    year: 1992,
    title: 'Residuos peligrosos',
    summary: 'Régimen nacional de generación, manipulación, transporte, tratamiento y disposición de residuos peligrosos.',
    topics: ['Ambiente', 'Residuos peligrosos'],
    modules: ['environment', 'hse', 'oil-gas'],
    organism: 'Congreso de la Nación Argentina',
    status: 'vigente',
    officialSourceLabel: 'Fuente oficial pendiente',
    tags: ['residuos', 'ambiente']
  },
  {
    id: 'neuquen-1875',
    jurisdiction: 'provincial',
    province: 'Neuquén',
    type: 'Ley Provincial',
    number: '1875',
    year: 1990,
    title: 'Medio Ambiente de la Provincia del Neuquén',
    summary: 'Referencia provincial ambiental para la jurisdicción de Neuquén. Usar solo cuando el informe corresponda a esa provincia.',
    topics: ['Ambiente', 'Neuquén'],
    modules: ['environment', 'hse', 'oil-gas'],
    organism: 'Provincia del Neuquén',
    status: 'vigente',
    officialSourceLabel: 'Fuente oficial pendiente',
    tags: ['provincial', 'ambiente']
  },
  {
    id: 'iso-45001',
    jurisdiction: 'referencia',
    type: 'Norma técnica',
    number: 'ISO 45001',
    year: 2018,
    title: 'Sistemas de gestión de seguridad y salud en el trabajo',
    summary: 'Norma de referencia para sistemas de gestión SST. No reemplaza normativa legal local.',
    topics: ['Gestión SST', 'Auditoría', 'Sistema de gestión'],
    modules: ['hse', 'audit'],
    organism: 'ISO',
    status: 'referencia',
    officialSourceLabel: 'Referencia técnica',
    tags: ['gestión', 'sst', 'auditoría']
  }
];
