import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useWorkspace } from '../../src/providers/workspace-provider';
import { listInspectionTemplates, listRecentInspectionRuns, seedInspectionTemplates, type InspectionRunSummary } from '../../src/services/inspections';
import type { FormTemplateSummary } from '../../src/types/forms';
import { theme } from '../../src/theme';

export default function InspectionsPage(){
  const{workspace}=useWorkspace();const[templates,setTemplates]=useState<FormTemplateSummary[]>([]);const[runs,setRuns]=useState<InspectionRunSummary[]>([]);const[loading,setLoading]=useState(false);const[seeding,setSeeding]=useState(false);
  const load=useCallback(async()=>{if(!workspace)return;setLoading(true);try{const[t,r]=await Promise.all([listInspectionTemplates(workspace),listRecentInspectionRuns(workspace)]);setTemplates(t);setRuns(r);}catch(e){Alert.alert('Inspecciones',e instanceof Error?e.message:'No se pudieron cargar');}finally{setLoading(false);}},[workspace]);
  useEffect(()=>{void load();},[load]);
  async function seed(){if(!workspace)return;setSeeding(true);try{const count=await seedInspectionTemplates(workspace);await load();Alert.alert('Biblioteca lista',count?`Se agregaron ${count} checklists operativos.`:'Los checklists estándar ya estaban disponibles.');}catch(e){Alert.alert('Biblioteca',e instanceof Error?e.message:'No se pudo preparar');}finally{setSeeding(false);}}
  return <ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={styles.content}>
    <Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Volver</Text></Pressable>
    <View style={styles.hero}><Text style={styles.kicker}>HSE · CAMPO</Text><Text style={styles.title}>Inspecciones</Text><Text style={styles.copy}>Checklist versionado, evidencia y hallazgos en el mismo circuito. Un “No cumple” nunca crea algo solo: vos decidís.</Text></View>
    <View style={styles.sectionRow}><Text style={styles.section}>Biblioteca activa</Text><Pressable disabled={seeding} onPress={()=>void seed()}><Text style={styles.seed}>{seeding?'Preparando…':'Agregar estándares'}</Text></Pressable></View>
    <View style={styles.grid}>{templates.map(item=><Pressable key={item.id} onPress={()=>router.push(`/forms/${item.id}`)} style={styles.card}><View style={styles.icon}><Text style={styles.iconText}>✓</Text></View><View style={{flex:1}}><Text style={styles.cardTitle}>{item.name}</Text><Text style={styles.cardCopy}>{item.description||item.schema.description||'Checklist HSE'}</Text><Text style={styles.cardMeta}>Versión {item.version} · publicada</Text></View><Text style={styles.chevron}>›</Text></Pressable>)}</View>
    {!templates.length&&!loading?<View style={styles.empty}><Text style={styles.emptyTitle}>Biblioteca vacía</Text><Text style={styles.emptyCopy}>Cargá los checklists estándar o creá plantillas específicas desde HSE Control Desktop.</Text><Pressable disabled={seeding} onPress={()=>void seed()} style={styles.primary}><Text style={styles.primaryText}>Preparar biblioteca inicial</Text></Pressable></View>:null}
    <Text style={styles.section}>Actividad reciente</Text>
    <View style={styles.history}>{runs.map(run=><Pressable key={run.id} onPress={()=>router.push(`/form-run/${run.id}`)} style={styles.run}><View><Text style={styles.runTitle}>{run.templateName}</Text><Text style={styles.runDate}>{new Date(run.started_at).toLocaleString('es-AR')}</Text></View><Text style={[styles.status,run.status==='submitted'&&styles.statusDone]}>{run.status==='submitted'?'ENVIADA':run.status.replace('_',' ').toUpperCase()}</Text></Pressable>)}{!runs.length?<Text style={styles.noRuns}>Todavía no hay inspecciones realizadas.</Text>:null}</View>
  </ScrollView>;
}
const styles=StyleSheet.create({content:{paddingTop:54,paddingHorizontal:18,paddingBottom:42,gap:15,backgroundColor:theme.colors.bg,minHeight:'100%'},back:{color:theme.colors.primary,fontWeight:'900'},hero:{backgroundColor:'#0F172A',borderRadius:24,padding:20,gap:5},kicker:{fontSize:10,fontWeight:'900',color:'#5EEAD4',letterSpacing:1.4},title:{fontSize:31,fontWeight:'900',color:'#fff'},copy:{color:'#CBD5E1',lineHeight:19},sectionRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'baseline'},section:{fontSize:18,fontWeight:'900',color:theme.colors.ink},seed:{fontSize:11,fontWeight:'900',color:theme.colors.primary},grid:{gap:9},card:{backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:17,padding:14,flexDirection:'row',alignItems:'center',gap:11},icon:{width:38,height:38,borderRadius:12,backgroundColor:'#ECFDF5',alignItems:'center',justifyContent:'center'},iconText:{fontSize:18,fontWeight:'900',color:'#047857'},cardTitle:{fontSize:15,fontWeight:'900',color:theme.colors.ink},cardCopy:{fontSize:11,color:theme.colors.muted,marginTop:2,lineHeight:16},cardMeta:{fontSize:10,color:theme.colors.primary,fontWeight:'800',marginTop:5},chevron:{fontSize:27,color:'#94A3B8'},empty:{backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:18,padding:22,alignItems:'center'},emptyTitle:{fontSize:17,fontWeight:'900',color:theme.colors.ink},emptyCopy:{color:theme.colors.muted,textAlign:'center',marginTop:4,lineHeight:18},primary:{backgroundColor:theme.colors.primary,paddingVertical:11,paddingHorizontal:15,borderRadius:11,marginTop:12},primaryText:{color:'#fff',fontWeight:'900'},history:{gap:8},run:{backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line,borderRadius:14,padding:13,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},runTitle:{fontWeight:'900',color:theme.colors.ink},runDate:{fontSize:10,color:theme.colors.muted,marginTop:2},status:{fontSize:9,fontWeight:'900',color:'#B45309',backgroundColor:'#FFFBEB',paddingHorizontal:8,paddingVertical:5,borderRadius:8},statusDone:{color:'#047857',backgroundColor:'#ECFDF5'},noRuns:{color:theme.colors.muted,fontSize:12}});
