'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { getCurrentHseUser, getHseWorkspace, type HseWorkspace } from '@/services/hse/browser';
import { createFormTemplate, listFormTemplates, publishFormVersion, type HseFormTemplate } from '@/services/hse/forms-browser';
import type { HseFormField, HseFormSchema } from '@/shared/hse/forms/types';

type DraftField={id:string;label:string;type:'compliance'|'text'|'photo'|'risk_matrix';required:boolean};
const shell:React.CSSProperties={minHeight:'100vh',background:'#f4f7f6',padding:'36px 24px',color:'#102a2a'};
const card:React.CSSProperties={background:'#fff',border:'1px solid #dbe4e2',borderRadius:18,padding:18,boxShadow:'0 8px 24px rgba(15,118,110,.05)'};
const input:React.CSSProperties={width:'100%',border:'1px solid #dbe4e2',borderRadius:11,padding:'11px 12px',font:'inherit',boxSizing:'border-box'};
const primary:React.CSSProperties={border:0,borderRadius:11,padding:'11px 15px',background:'#0f766e',color:'#fff',fontWeight:800,cursor:'pointer'};
const ghost:React.CSSProperties={border:'1px solid #cbd5e1',borderRadius:10,padding:'9px 12px',background:'#fff',fontWeight:750,cursor:'pointer',color:'#334155'};

export default function HseFormsPage(){
  const[workspace,setWorkspace]=useState<HseWorkspace|null>(null);const[templates,setTemplates]=useState<HseFormTemplate[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
  const[name,setName]=useState('');const[category,setCategory]=useState('inspection');const[description,setDescription]=useState('');const[sectionTitle,setSectionTitle]=useState('Verificación');const[fields,setFields]=useState<DraftField[]>([{id:'item_1',label:'Condición verificada',type:'compliance',required:true},{id:'evidence',label:'Evidencia fotográfica',type:'photo',required:false}]);
  const load=useCallback(async()=>{setError(null);const user=await getCurrentHseUser();if(!user){setError('Ingresá primero a HSE Control.');return;}const ws=await getHseWorkspace();setWorkspace(ws);if(ws)setTemplates(await listFormTemplates(ws));},[]);
  useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'Error'));},[load]);
  const schema=useMemo<HseFormSchema>(()=>({version:1,title:name.trim()||'Nueva plantilla',description:description.trim()||undefined,category,sections:[{id:'main',title:sectionTitle.trim()||'Verificación',fields:fields.map(field=>field.type==='compliance'?{...field,createFindingOnFail:true}:field) as HseFormField[]}]}),[name,description,category,sectionTitle,fields]);
  function addField(type:DraftField['type']){setFields(current=>[...current,{id:`field_${Date.now()}`,label:type==='photo'?'Evidencia':type==='risk_matrix'?'Nivel de riesgo':'Nueva verificación',type,required:type!=='photo'}]);}
  async function createAndPublish(){if(!workspace||!name.trim())return;setBusy(true);setError(null);try{const created=await createFormTemplate(workspace,{name,category,description,schema});await publishFormVersion(created.versionId);setName('');setDescription('');setFields([{id:'item_1',label:'Condición verificada',type:'compliance',required:true},{id:'evidence',label:'Evidencia fotográfica',type:'photo',required:false}]);await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo publicar');}finally{setBusy(false);}}
  return <main style={shell}><div style={{maxWidth:1180,margin:'0 auto',display:'grid',gap:18}}>
    <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16}}><div><div style={{fontSize:11,fontWeight:900,letterSpacing:1.5,color:'#0f766e'}}>INFORME360 · CONFIGURACIÓN</div><h1 style={{margin:'4px 0 0',fontSize:34}}>Motor de formularios HSE</h1><p style={{margin:'6px 0 0',color:'#64748b'}}>Creá una vez. Usalo en inspecciones, IPCR, permisos e investigaciones sin programar otra pantalla.</p></div><Link href="/app/hse" style={{...ghost,textDecoration:'none'}}>← Command Center</Link></header>
    {error?<div style={{...card,borderColor:'#fecaca',background:'#fef2f2',color:'#991b1b'}}>{error}</div>:null}
    <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.15fr) minmax(320px,.85fr)',gap:18}}>
      <div style={{...card,display:'grid',gap:13}}><div><b style={{fontSize:19}}>Nueva plantilla</b><div style={{color:'#64748b',fontSize:13,marginTop:3}}>La primera publicación queda inmutable. Los cambios futuros generan una nueva versión.</div></div>
        <label>Nombre<input style={input} value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Inspección de trabajo en altura"/></label>
        <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label>Categoría<select style={input} value={category} onChange={e=>setCategory(e.target.value)}><option value="inspection">Inspección</option><option value="checklist">Checklist</option><option value="ipcr">IPCR</option><option value="permit">Permiso</option><option value="incident">Incidente</option></select></label><label>Sección<input style={input} value={sectionTitle} onChange={e=>setSectionTitle(e.target.value)}/></label></div>
        <label>Descripción<textarea style={{...input,minHeight:74,resize:'vertical'}} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Objetivo y alcance"/></label>
        <div style={{display:'grid',gap:8}}>{fields.map((field,index)=><div key={field.id} style={{display:'grid',gridTemplateColumns:'1fr 150px 92px 34px',gap:7,alignItems:'center',padding:9,border:'1px solid #e2e8f0',borderRadius:11}}><input style={input} value={field.label} onChange={e=>setFields(current=>current.map((item,i)=>i===index?{...item,label:e.target.value}:item))}/><select style={input} value={field.type} onChange={e=>setFields(current=>current.map((item,i)=>i===index?{...item,type:e.target.value as DraftField['type']}:item))}><option value="compliance">Cumplimiento</option><option value="text">Texto</option><option value="photo">Foto</option><option value="risk_matrix">Riesgo</option></select><label style={{fontSize:12,color:'#64748b'}}><input type="checkbox" checked={field.required} onChange={e=>setFields(current=>current.map((item,i)=>i===index?{...item,required:e.target.checked}:item))}/> obligatorio</label><button style={{...ghost,padding:7}} onClick={()=>setFields(current=>current.filter((_,i)=>i!==index))}>×</button></div>)}</div>
        <div style={{display:'flex',gap:7,flexWrap:'wrap'}}><button style={ghost} onClick={()=>addField('compliance')}>+ Cumplimiento</button><button style={ghost} onClick={()=>addField('text')}>+ Texto</button><button style={ghost} onClick={()=>addField('photo')}>+ Foto</button><button style={ghost} onClick={()=>addField('risk_matrix')}>+ Matriz de riesgo</button></div>
        <button style={{...primary,opacity:busy||!name.trim()?.55:1}} disabled={busy||!name.trim()} onClick={()=>void createAndPublish()}>{busy?'Publicando…':'Crear y publicar v1'}</button>
      </div>
      <aside style={{...card,alignSelf:'start'}}><div style={{fontSize:11,fontWeight:900,color:'#0f766e',letterSpacing:1}}>PREVIEW DEL CONTRATO</div><h2 style={{margin:'6px 0'}}>{schema.title}</h2><p style={{color:'#64748b'}}>{schema.description||'Sin descripción'}</p><div style={{display:'grid',gap:7,marginTop:14}}>{schema.sections[0].fields.map(field=><div key={field.id} style={{padding:10,border:'1px solid #e2e8f0',borderRadius:10}}><b>{field.label}</b><div style={{fontSize:11,color:'#64748b',marginTop:2}}>{field.type}{field.required?' · obligatorio':''}</div></div>)}</div></aside>
    </section>
    <section style={card}><div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline'}}><div><b style={{fontSize:19}}>Plantillas</b><div style={{fontSize:12,color:'#64748b',marginTop:2}}>{workspace?.organizationName||'Organización'} · {templates.length} registradas</div></div><button style={ghost} onClick={()=>void load()}>Actualizar</button></div><div style={{display:'grid',gap:8,marginTop:14}}>{templates.map(item=><div key={item.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:13,border:'1px solid #e2e8f0',borderRadius:12}}><div><b>{item.name}</b><div style={{fontSize:11,color:'#64748b',marginTop:2}}>{item.category} · {item.publishedVersion?`publicada v${item.publishedVersion.version}`:'sin versión publicada'}</div></div><span style={{fontSize:10,fontWeight:900,color:item.status==='active'?'#047857':'#64748b'}}>{item.status.toUpperCase()}</span></div>)}{!templates.length?<div style={{color:'#64748b',padding:12}}>Todavía no hay plantillas.</div>:null}</div></section>
  </div></main>;
}
