import { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useWorkspace } from '../../src/providers/workspace-provider';
import { listFindings } from '../../src/services/findings';
import { FindingCard } from '../../src/components/FindingCard';
import type { Finding } from '../../src/types/hse';
import { theme } from '../../src/theme';

type Filter = 'open' | 'overdue' | 'closed' | 'all';
export default function Findings() { const { workspace } = useWorkspace(); const [items,setItems]=useState<Finding[]>([]); const [filter,setFilter]=useState<Filter>('open'); const [busy,setBusy]=useState(false); const load=useCallback(async()=>{if(!workspace)return;setBusy(true);try{setItems(await listFindings(workspace));}finally{setBusy(false)}},[workspace]); useEffect(()=>{void load()},[load]); const visible=useMemo(()=>{const now=Date.now();if(filter==='closed')return items.filter(x=>x.status==='closed');if(filter==='overdue')return items.filter(x=>!['closed','cancelled'].includes(x.status)&&!!x.due_at&&new Date(x.due_at).getTime()<now);if(filter==='open')return items.filter(x=>!['closed','cancelled'].includes(x.status));return items},[items,filter]); return <View style={styles.safe}><ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={styles.content}><Text style={styles.title}>Hallazgos</Text><View style={styles.filters}>{(['open','overdue','closed','all'] as Filter[]).map(f=><Pressable key={f} onPress={()=>setFilter(f)} style={[styles.filter,filter===f&&styles.active]}><Text style={[styles.filterText,filter===f&&styles.activeText]}>{({open:'Abiertos',overdue:'Vencidos',closed:'Cerrados',all:'Todos'} as const)[f]}</Text></Pressable>)}</View>{visible.map(f=><FindingCard key={f.id} finding={f} onPress={()=>router.push(`/finding/${f.id}`)}/>)}{!visible.length&&!busy?<Text style={styles.empty}>No hay registros en esta vista.</Text>:null}</ScrollView></View> }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.bg},content:{paddingTop:58,paddingHorizontal:18,paddingBottom:30,gap:12},title:{fontSize:30,fontWeight:'900',color:theme.colors.ink},filters:{flexDirection:'row',gap:7,flexWrap:'wrap'},filter:{paddingHorizontal:12,paddingVertical:8,borderRadius:999,backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.line},active:{backgroundColor:theme.colors.primary,borderColor:theme.colors.primary},filterText:{fontSize:12,fontWeight:'800',color:theme.colors.muted},activeText:{color:'#fff'},empty:{textAlign:'center',color:theme.colors.muted,padding:30}});
