import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useWorkspace } from '../../src/providers/workspace-provider';
import { useAuth } from '../../src/providers/auth-provider';
import { listFindings } from '../../src/services/findings';
import type { Finding } from '../../src/types/hse';
import { FindingCard } from '../../src/components/FindingCard';
import { theme } from '../../src/theme';

export default function Home() {
  const { workspace } = useWorkspace(); const { signOut } = useAuth(); const [items, setItems] = useState<Finding[]>([]); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { if (!workspace) return; setBusy(true); try { setItems(await listFindings(workspace)); } catch (e) { Alert.alert('No se pudieron cargar hallazgos', e instanceof Error ? e.message : 'Error'); } finally { setBusy(false); } }, [workspace]);
  useEffect(() => { void load(); }, [load]);
  const metrics = useMemo(() => { const now = Date.now(); return { overdue: items.filter(x => !['closed','cancelled'].includes(x.status) && x.due_at && new Date(x.due_at).getTime() < now).length, upcoming: items.filter(x => !['closed','cancelled'].includes(x.status) && x.due_at && new Date(x.due_at).getTime() >= now).length, closed: items.filter(x => x.status === 'closed').length }; }, [items]);
  return <View style={styles.safe}><ScrollView refreshControl={<RefreshControl refreshing={busy} onRefresh={load}/>} contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.kicker}>HSE COPILOT</Text><Text style={styles.title}>{workspace?.siteName || 'Campo'}</Text><Text style={styles.subtitle}>{workspace?.organizationName}</Text></View><Pressable onPress={() => void signOut()}><Text style={styles.exit}>Salir</Text></Pressable></View><Pressable onPress={() => router.push('/register')} style={styles.register}><Text style={styles.mic}>🎙️</Text><Text style={styles.registerTitle}>REGISTRAR</Text><Text style={styles.registerCopy}>Voz · foto · texto</Text></Pressable><View style={styles.metrics}><Metric label="Vencidos" value={metrics.overdue} tone={theme.colors.danger}/><Metric label="Próximos" value={metrics.upcoming} tone={theme.colors.warning}/><Metric label="Cerrados" value={metrics.closed} tone={theme.colors.success}/></View><Text style={styles.section}>Actividad reciente</Text>{items.slice(0, 5).map((finding) => <FindingCard key={finding.id} finding={finding} onPress={() => router.push(`/finding/${finding.id}`)}/>)}{!items.length && !busy ? <Text style={styles.empty}>Todavía no hay hallazgos. Tocá REGISTRAR y cargá el primero.</Text> : null}</ScrollView></View>;
}
function Metric({ label, value, tone }: { label: string; value: number; tone: string }) { return <View style={styles.metric}><Text style={[styles.metricValue, { color: tone }]}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: theme.colors.bg }, content: { paddingTop: 58, paddingHorizontal: 18, paddingBottom: 30, gap: 14 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, kicker: { color: theme.colors.primary, fontWeight: '900', letterSpacing: 1.8, fontSize: 11 }, title: { fontSize: 28, fontWeight: '900', color: theme.colors.ink }, subtitle: { color: theme.colors.muted }, exit: { color: theme.colors.muted, fontWeight: '700' }, register: { backgroundColor: theme.colors.primary, minHeight: 190, borderRadius: 28, alignItems: 'center', justifyContent: 'center', marginTop: 8 }, mic: { fontSize: 44 }, registerTitle: { color: '#fff', fontSize: 24, fontWeight: '900', letterSpacing: 1 }, registerCopy: { color: '#CCFBF1', marginTop: 6 }, metrics: { flexDirection: 'row', gap: 8 }, metric: { flex: 1, backgroundColor: '#fff', padding: 14, borderRadius: 16, borderWidth: 1, borderColor: theme.colors.line }, metricValue: { fontSize: 26, fontWeight: '900' }, metricLabel: { color: theme.colors.muted, fontSize: 12, fontWeight: '700' }, section: { fontSize: 18, fontWeight: '900', color: theme.colors.ink, marginTop: 8 }, empty: { color: theme.colors.muted, textAlign: 'center', padding: 24, lineHeight: 21 } });
