import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { DynamicForm } from '../../src/components/forms/DynamicForm';
import { getFormRunBundle, submitFormRun } from '../../src/services/forms';
import { removeOfflineFormDraft, saveOfflineFormDraft } from '../../src/services/form-offline';
import { createFindingFromNonCompliance, linkedFindingsForRun } from '../../src/services/inspections';
import type { FormRunBundle, HseFormAnswers } from '../../src/types/forms';
import { theme } from '../../src/theme';

export default function FormRunPage(){
  const {runId}=useLocalSearchParams<{runId:string}>();
  const [bundle,setBundle]=useState<FormRunBundle|null>(null);
  const [answers,setAnswers]=useState<HseFormAnswers>({});
  const [linked,setLinked]=useState<Record<string,string>>({});
  const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!runId)return;try{const[next,links]=await Promise.all([getFormRunBundle(runId),linkedFindingsForRun(runId)]);setBundle(next);setAnswers(next.answers);setLinked(Object.fromEntries(links.map(item=>[item.field_id,item.finding_id])));}catch(error){Alert.alert('Formulario',error instanceof Error?error.message:'No se pudo cargar');}},[runId]);
  useEffect(()=>{void load();},[load]);
  const failures=useMemo(()=>{if(!bundle)return[];return bundle.version.schema_json.sections.flatMap(section=>section.fields).filter(field=>field.type==='compliance'&&field.createFindingOnFail===true&&answers[field.id]==='non_compliant').map(field=>({id:field.id,label:field.label}));},[bundle,answers]);
  async function persistLocal(next:HseFormAnswers){if(!bundle||!runId)return;setAnswers(next);await saveOfflineFormDraft({clientRunId:runId,serverRunId:runId,templateVersionId:bundle.version.id,templateId:bundle.template.id,siteId:bundle.run.site_id,answers:next});}
  async function submit(next:HseFormAnswers){if(!bundle||!runId)return;setBusy(true);try{await submitFormRun(runId,next);await removeOfflineFormDraft(runId);await load();Alert.alert('Formulario enviado',bundle.template.category==='inspection'?'La inspección quedó registrada. Revisá abajo los ítems No cumple y decidí cuáles deben convertirse en hallazgo.':'Las respuestas quedaron registradas y versionadas.');}catch(error){await persistLocal(next);Alert.alert('Guardado en el teléfono','No pudimos enviar ahora. El formulario quedó guardado localmente y no se enviará sin tu confirmación.',[{text:'Entendido'}]);}finally{setBusy(false);}}
  async function makeFinding(fieldId:string,label:string){if(!runId)return;setBusy(true);try{const findingId=await createFindingFromNonCompliance(runId,fieldId,label);setLinked(current=>({...current,[fieldId]:findingId}));Alert.alert('Hallazgo creado','La no conformidad quedó vinculada al sistema de hallazgos.',[{text:'Abrir',onPress:()=>router.push(`/finding/${findingId}`)},{text:'Seguir'}]);}catch(error){Alert.alert('Hallazgo',error instanceof Error?error.message:'No se pudo crear');}finally{setBusy(false);}}
  if(!bundle)return <View style={styles.loading}><Text>Cargando ejecución…</Text></View>;
  const readOnly=['submitted','reviewed','cancelled'].includes(bundle.run.status);
  return <ScrollView contentContainerStyle={styles.content}>
    <View style={styles.top}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Volver</Text></Pressable><Text style={styles.status}>{bundle.run.status.toUpperCase()}</Text></View>
    <View><Text style={styles.kicker}>{bundle.template.category.toUpperCase()} · v{bundle.version.version}</Text><Text style={styles.title}>{bundle.template.name}</Text><Text style={styles.copy}>Iniciado {new Date(bundle.run.started_at).toLocaleString('es-AR')}</Text></View>
    <DynamicForm schema={bundle.version.schema_json} initialAnswers={answers} readOnly={readOnly} submitLabel={busy?'Guardando…':'Enviar formulario'} onChange={next=>{if(!readOnly)void persistLocal(next);}} onSubmit={submit}/>
    {readOnly&&bundle.template.category==='inspection'?<View style={styles.failures}><View><Text style={styles.failuresTitle}>No conformidades</Text><Text style={styles.failuresCopy}>Nada se transforma automáticamente en hallazgo. Elegí qué requiere seguimiento formal.</Text></View>{failures.map(item=><View key={item.id} style={styles.failureRow}><View style={{flex:1}}><Text style={styles.failureLabel}>{item.label}</Text><Text style={styles.failureState}>{linked[item.id]?'Hallazgo vinculado':'Marcado como No cumple'}</Text></View>{linked[item.id]?<Pressable onPress={()=>router.push(`/finding/${linked[item.id]}`)} style={styles.openFinding}><Text style={styles.openFindingText}>Abrir</Text></Pressable>:<Pressable disabled={busy} onPress={()=>void makeFinding(item.id,item.label)} style={styles.makeFinding}><Text style={styles.makeFindingText}>Crear hallazgo</Text></Pressable>}</View>)}{!failures.length?<Text style={styles.noFailures}>No se registraron ítems “No cumple” configurados para generar hallazgos.</Text>:null}</View>:null}
    {readOnly?<View style={styles.locked}><Text style={styles.lockedTitle}>Ejecución cerrada para edición</Text><Text style={styles.lockedCopy}>Las respuestas corresponden a una versión histórica de la plantilla y permanecen auditables.</Text></View>:null}
  </ScrollView>;
}
const styles=StyleSheet.create({loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:theme.colors.bg},content:{paddingTop:54,paddingHorizontal:18,paddingBottom:44,gap:16,backgroundColor:theme.colors.bg,minHeight:'100%'},top:{flexDirection:'row',justifyContent:'space-between'},back:{color:theme.colors.primary,fontWeight:'900'},status:{fontSize:10,fontWeight:'900',color:theme.colors.muted,letterSpacing:1},kicker:{fontSize:10,fontWeight:'900',color:theme.colors.primary,letterSpacing:1.2},title:{fontSize:28,fontWeight:'900',color:theme.colors.ink,marginTop:2},copy:{fontSize:11,color:theme.colors.muted,marginTop:3},failures:{backgroundColor:'#FFF7ED',borderWidth:1,borderColor:'#FED7AA',borderRadius:17,padding:14,gap:10},failuresTitle:{fontSize:17,fontWeight:'900',color:'#9A3412'},failuresCopy:{fontSize:11,color:'#C2410C',marginTop:2,lineHeight:16},failureRow:{backgroundColor:'#fff',borderRadius:12,padding:11,flexDirection:'row',gap:9,alignItems:'center'},failureLabel:{fontSize:12,fontWeight:'900',color:theme.colors.ink},failureState:{fontSize:10,color:theme.colors.muted,marginTop:2},makeFinding:{backgroundColor:'#EA580C',paddingVertical:9,paddingHorizontal:10,borderRadius:9},makeFindingText:{color:'#fff',fontSize:10,fontWeight:'900'},openFinding:{borderWidth:1,borderColor:theme.colors.primary,paddingVertical:8,paddingHorizontal:12,borderRadius:9},openFindingText:{color:theme.colors.primary,fontSize:10,fontWeight:'900'},noFailures:{fontSize:11,color:'#9A3412'},locked:{backgroundColor:'#F8FAFC',borderRadius:14,padding:14,borderWidth:1,borderColor:theme.colors.line},lockedTitle:{fontWeight:'900',color:theme.colors.ink},lockedCopy:{fontSize:11,color:theme.colors.muted,marginTop:3,lineHeight:16}});
